spring:
  output:
    ansi:
      enabled: always

paths:
  dir_path: /Users/atran/GRM/mock-jira-api/contact-gen
  arch_path: /Users/atran/GRM/mock-jira-api/contacts
  img_path: /Users/atran/GRM/mock-jira-api/contact-png

arch: 
  refresh_sec: 5
  mark_archive_time_sec: 600

jira:
  url: http://vmoc-proj1.nrl.navy.mil:8080
  auth: Bearer OTY5Njk2Mzg2NzA4Oh0amfT2mfNUjmNrlL/zR0uRroQr
  main_proj_key: MAIN
