spring:
  main:
    web-application-type: none

paths:
  dir_path: C:\\Users\\rebed\\Work\\mock-jira-api\\contact-gen
  arch_path: C:\\Users\\rebed\\Work\\mock-jira-api\\contacts

arch: 
  refresh_sec: 5
  mark_archive_time_sec: 30